# Generated by Django 3.2.2 on 2021-05-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Desgination', models.CharField(max_length=30)),
                ('Hospital', models.CharField(max_length=30)),
                ('is_online', models.BooleanField(default=True)),
            ],
        ),
    ]
